name: Deploy MarascoFSC Infrastructure and Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    outputs:
      cloudfront-distribution-id: ${{ steps.terraform-outputs.outputs.distribution-id }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHubActions-Infrastructure
        aws-region: us-east-1
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.6.0"
        terraform_wrapper: false

    - name: Setup Terraform state storage
      run: |
        # Check if bucket exists for state storage, if not Terraform will create it
        echo "Terraform will manage S3 bucket creation and configuration"

    - name: Terraform Init
      working-directory: ./iac
      run: terraform init

    - name: Terraform Plan
      working-directory: ./iac
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: ./iac
      run: terraform apply -auto-approve tfplan

    - name: Get Terraform outputs
      id: terraform-outputs
      working-directory: ./iac
      run: |
        DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id)
        echo "distribution-id=$DISTRIBUTION_ID" >> $GITHUB_OUTPUT
        echo "CloudFront Distribution ID: $DISTRIBUTION_ID"

  deploy-website:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHubActions-Deploy
        aws-region: us-east-1
        
    - name: Sync to S3 with optimal caching
      run: |
        # Clean the entire bucket first (remove all files)
        echo "Cleaning S3 bucket..."
        aws s3 rm s3://marascofsc-website-2025 --recursive || true
        
        # Upload HTML files with short cache
        echo "Uploading HTML files..."
        aws s3 cp index.html s3://marascofsc-website-2025/index.html \
          --cache-control "public, max-age=300" \
          --content-type "text/html"
        
        # Upload CSS files with correct content type and long cache
        echo "Uploading CSS files..."
        if [ -d "css" ]; then
          for file in css/*.css; do
            if [ -f "$file" ]; then
              aws s3 cp "$file" "s3://marascofsc-website-2025/$file" \
                --cache-control "public, max-age=31536000" \
                --content-type "text/css"
            fi
          done
        fi
        
        # Upload JS files with correct content type and long cache
        echo "Uploading JS files..."
        if [ -d "js" ]; then
          for file in js/*.js; do
            if [ -f "$file" ]; then
              aws s3 cp "$file" "s3://marascofsc-website-2025/$file" \
                --cache-control "public, max-age=31536000" \
                --content-type "application/javascript"
            fi
          done
        fi
        
        # Upload media files with long cache
        echo "Uploading media files..."
        if [ -d "media" ]; then
          aws s3 sync media s3://marascofsc-website-2025/media \
            --cache-control "public, max-age=31536000"
        fi
        
        # List uploaded files for verification
        echo "Verifying uploaded files..."
        aws s3 ls s3://marascofsc-website-2025 --recursive
          
    - name: Invalidate CloudFront cache
      run: |
        DISTRIBUTION_ID="${{ needs.deploy-infrastructure.outputs.cloudfront-distribution-id }}"
        if [ ! -z "$DISTRIBUTION_ID" ] && [ "$DISTRIBUTION_ID" != "None" ]; then
          echo "Invalidating CloudFront distribution: $DISTRIBUTION_ID"
          aws cloudfront create-invalidation \
            --distribution-id "$DISTRIBUTION_ID" \
            --paths "/*"
        else
          echo "No CloudFront distribution ID available"
        fi